site_name: OpenMPF
theme: readthedocs
copyright: OpenMPF

markdown_extensions:
- toc

extra_javascript: [js/mustache.js]

use_directory_urls: false

pages:
- Home: index.md
- General:
    - Release Notes: Release-Notes.md
    - Build Guide: Build-Environment-Setup-Guide.md
    - Install Guide: Installation-Guide.md
    - User Guide: User-Guide.md
    - Admin Guide: Admin-Manual.md
    - Contributor Guide: Contributor-Guide.md
    - Acknowledgements: Acknowledgements.md
- Components:
    - Component API Overview: Component-API-Overview.md
    - C++ Batch Component API: CPP-Batch-Component-API.md
    - C++ Streaming Component API: CPP-Streaming-Component-API.md
    - Java Batch Component API: Java-Batch-Component-API.md
    - Packaging and Registering a Component: Packaging-and-Registering-a-Component.md
    - Feed Forward Guide: Feed-Forward-Guide.md
    - GPU Support Guide: GPU-Support-Guide.md
- Architecture:
    - Workflow Manager: Workflow-Manager.md
    - REST API: REST-API.md
